# Generated by Django 4.2.11 on 2024-03-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=32)),
                ("pwd", models.CharField(max_length=32)),
                ("_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "用戶資料庫",
                "verbose_name_plural": "用戶資料庫",
                "ordering": ["-_time"],
            },
        ),
    ]
