# Generated by Django 4.2.11 on 2024-03-30 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_user_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth",
        ),
    ]
