# Generated by Django 4.2.11 on 2024-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_remove_user_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
